### ISSUE TITLE
Implémenter le MDS

### ISSUE THREAD

**Issue by SIben** [clemux/psychic-spice#3]
http://stackoverflow.com/questions/16990996/multidimensional-scaling-fitting-in-numpy-pandas-and-sklearn-valueerror
http://en.wikipedia.org/wiki/Multidimensional_scaling

**Comment by clemux** [comment]
- http://scikit-learn.org/stable/auto_examples/manifold/plot_mds.html
 - http://www.nervouscomputer.com/hfs/cmdscale-in-python/
 - http://baoilleach.blogspot.fr/2014/01/convert-distance-matrix-to-2d.html
 - http://baoilleach.blogspot.fr/2014/01/convert-distance-matrix-to-2d.html
